### ISSUE TITLE
Can't delete notes

### ISSUE THREAD

**Issue by nsiti** [baggachipz/tinylist#19] opened 2021-04-06 21:07 UTC
Notes are not being deleted by clicking the trash icon.
Using ungoogled chromium browser.

**Comment by baggachipz** [comment] 2021-04-07 18:10
Are you using this on multiple platforms? I have seen it before where if an item is out of sync then deleting creates an error (in the console). Can you paste any errors you may see?

**Comment by nsiti** [comment] 2021-04-07 19:37
Hi, it may have been a server issue yesterday. I can't reproduce the error today. No errors showed up when the problem presented itself. I'm not using TinyList on multiple platforms, but rather on various computers that are on, but not active simultaneously.

One unrelated thing, carriage returns in notes do not separate lines in the previews of the notes, but do when the notes are open. To separate lines in the preview, a full empty line must be present, which then takes up more space. It would be great if you could look into this as a future "feature," thanks.

**Comment by baggachipz** [comment] 2021-04-08 01:45
This is the one negative consequence of enabling Markdown support. It takes two carriage returns to create a new paragraph. There's not really a way around it, except to remove that support but I can't really do that at this point. I also don't want to add a WYSIWYG editor because it would send me into a spiral of shame. I've kind of painted myself into a corner there. :/

**Comment by nsiti** [comment] 2021-04-08 13:58
Got it, thank you for your reply. Appreciate the effort!

**Comment by baggachipz** [comment] 2021-04-08 14:19
Cool if I close the issue then? If you are able to reproduce the delete problem, I'd love to get it nailed down.

**Comment by nsiti** [comment] 2021-04-08 14:25
Yes, thank you.

**Comment by baggachipz** [comment] 2021-04-08 14:27
Great, thank you for the report!

**Closed by baggachipz** 2021-04-08 14:27 UTC
